#coding=utf8
import redis
r = redis.Redis(host='192.168.1.1',port=6379,db=5)
#print r.keys()
r1 = redis.Redis(host='192.168.1.2',port=6379,db=5)
#print r1.keys()

print  r1.hgetall('MONTYLY_PHONEBILL_NOTIFY_KEY')['MONTHLY_PHONEBILL_NOTIFY']
#print  r1.hset('MONTYLY_PHONEBILL_NOTIFY_KEY','MONTHLY_PHONEBILL_NOTIFY','2016-04-05 00:00:00')

#print  r1.ttl('PROVINCE_DAY_ACCOUNT_b931a766aae04f77986e320d96368339_320000_000000000000000000')
#print  r.ttl('SMS_USER_TRANS_ACCOUT_DAY')
#print r.get('INVOKE_USER_CREDIT_COUNT_201511_read189')
#print  r.hget('SMS_USER_TRANS_ACCOUT_DAY','330000_15336554557_1')
#print  r.hgetall('SMS_USER_TRANS_ACCOUT_DAY')
#print  r1.hget('DUNANDAI_USER_TRANS_ACCOUT_DAY','8fa021e78d946f560dbf8490c9021e2c_13318353922')
#print r1.hgetall('DUNANDAI_USER_TRANS_ACCOUT_DAY')
def DAY_MONTH_ttl():
    #a1 = r.ttl('SMSPAY_APP_TRANS_ACCOUNT_DAY')
    a2 = r1.ttl('SMSPAY_CHANNEL_TRANS_ACCOUNT_DAY')
    #print a2
    a3 = r1.ttl('SMSPAY_USER_TRANS_ACCOUNT_DAY')
    #print a3
    #b1 = r1.ttl('SMSPAY_APP_TRANS_ACCOUNT_MONTH')
    b2 = r1.ttl('SMSPAY_USER_TRANS_ACCOUNT_MONTH')
    #print b2
    b3 = r.ttl('SMSPAY_CHANNEL_TRANS_ACCOUNT_MONTH')
    #print b3
    
    a=[a2,a3]
    b=[b2,b3]
    #print a
    #print b
    if abs(max(a)-min(a))<=2 and abs(max(b)-min(b))<=2:
    #if r.ttl('SMS_USER_TRANS_ACCOUT_DAY')==r.ttl('SMS_USER_TRANS_COUNT_DAY')==r1.ttl('DUNANDAI_USER_TRANS_ACCOUT_DAY')==r1.ttl('DUNANDAI_USER_TRANS_COUNT_DAY')>0 and r1.ttl('SMS_USER_TRANS_ACCOUT_MONTH')==r1.ttl('SMS_USER_TRANS_COUNT_MONTH')==r1.ttl('DUNANDAI_USER_TRANS_ACCOUT_MONTH')==r1.ttl('DUNANDAI_USER_TRANS_COUNT_MONTH')>0:  
        return 'PASS'
    else:
        return 'SMS_USER_TRANS_ACCOUT_DAY='+str(r.ttl('SMS_USER_TRANS_ACCOUT_DAY'))+',SMS_USER_TRANS_COUNT_DAY='+str(r.ttl('SMS_USER_TRANS_COUNT_DAY'))+',DUNANDAI_USER_TRANS_ACCOUT_DAY='+str(r1.ttl('DUNANDAI_USER_TRANS_ACCOUT_DAY'))+',DUNANDAI_USER_TRANS_COUNT_DAY='+str(r1.ttl('DUNANDAI_USER_TRANS_COUNT_DAY'))+',SMS_USER_TRANS_ACCOUT_MONTH='+str(r1.ttl('SMS_USER_TRANS_ACCOUT_MONTH'))+',SMS_USER_TRANS_COUNT_MONTH='+str(r1.ttl('SMS_USER_TRANS_COUNT_MONTH'))+',DUNANDAI_USER_TRANS_ACCOUT_MONTH='+str(r1.ttl('DUNANDAI_USER_TRANS_ACCOUT_MONTH'))+',DUNANDAI_USER_TRANS_COUNT_MONTH='+str(r1.ttl('DUNANDAI_USER_TRANS_COUNT_MONTH'))
#print DAY_MONTH_ttl()
